// Kumpulan 100 soal pemula tentang pembuatan website (Bahasa Indonesia)
// Format: { id, question_text, options, correct_answer }

export type Question = {
    id: number;
    question_text: string;
    options: string[];
    correct_answer: string; // harus sama dengan salah satu item di options
};

export const questions: Question[] = [
    {
        id: 1,
        question_text: "Apa kepanjangan dari HTML?",
        options: [
            "HyperText Markup Language",
            "HighText Machine Language",
            "Hyperlink and Text Markup Language",
            "Home Tool Markup Language",
        ],
        correct_answer: "HyperText Markup Language",
    },
    {
        id: 2,
        question_text: "Tag HTML untuk membuat paragraf adalah?",
        options: ["<p>", "<para>", "<paragraph>", "<pg>"],
        correct_answer: "<p>",
    },
    {
        id: 3,
        question_text: "Tag HTML untuk membuat tautan adalah?",
        options: ["<a>", "<link>", "<href>", "<url>"],
        correct_answer: "<a>",
    },
    {
        id: 4,
        question_text: "Tag HTML untuk menampilkan gambar adalah?",
        options: ["<img>", "<image>", "<picture>", "<photo>"],
        correct_answer: "<img>",
    },
    {
        id: 5,
        question_text: "Atribut pada <img> untuk teks alternatif adalah?",
        options: ["alt", "title", "text", "label"],
        correct_answer: "alt",
    },
    {
        id: 6,
        question_text: "Tag judul (heading) terbesar adalah?",
        options: ["<h1>", "<h6>", "<header>", "<title>"],
        correct_answer: "<h1>",
    },
    {
        id: 7,
        question_text: "Tag untuk daftar tidak berurutan adalah?",
        options: ["<ul>", "<ol>", "<li>", "<dl>"],
        correct_answer: "<ul>",
    },
    {
        id: 8,
        question_text: "Tag untuk daftar berurutan adalah?",
        options: ["<ol>", "<ul>", "<li>", "<dt>"],
        correct_answer: "<ol>",
    },
    {
        id: 9,
        question_text: "Elemen semantik untuk konten utama halaman adalah?",
        options: ["<main>", "<section>", "<article>", "<div>"],
        correct_answer: "<main>",
    },
    {
        id: 10,
        question_text: "Elemen semantik untuk navigasi adalah?",
        options: ["<nav>", "<menu>", "<header>", "<aside>"],
        correct_answer: "<nav>",
    },
    {
        id: 11,
        question_text: "Elemen semantik untuk bagian kaki halaman adalah?",
        options: ["<footer>", "<bottom>", "<end>", "<down>"],
        correct_answer: "<footer>",
    },
    {
        id: 12,
        question_text: "Elemen semantik untuk bagian kepala halaman adalah?",
        options: ["<header>", "<head>", "<hgroup>", "<top>"],
        correct_answer: "<header>",
    },
    {
        id: 13,
        question_text: "Elemen semantik yang mewakili konten mandiri seperti posting blog adalah?",
        options: ["<article>", "<section>", "<div>", "<span>"],
        correct_answer: "<article>",
    },
    {
        id: 14,
        question_text: "Elemen semantik untuk mengelompokkan bagian bertema dalam halaman adalah?",
        options: ["<section>", "<group>", "<div>", "<aside>"],
        correct_answer: "<section>",
    },
    {
        id: 15,
        question_text: "Atribut pada <a> untuk membuka tautan di tab baru adalah?",
        options: ["target=\"_blank\"", "open=\"new\"", "newtab", "rel=\"_blank\""],
        correct_answer: "target=\"_blank\"",
    },
    {
        id: 16,
        question_text: "Atribut pada <a> untuk menentukan alamat tujuan adalah?",
        options: ["href", "src", "url", "to"],
        correct_answer: "href",
    },
    {
        id: 17,
        question_text: "Atribut pada <img> untuk sumber gambar adalah?",
        options: ["src", "href", "link", "source"],
        correct_answer: "src",
    },
    {
        id: 18,
        question_text: "Tag untuk menautkan berkas CSS eksternal adalah?",
        options: ["<link>", "<style>", "<script>", "<css>"],
        correct_answer: "<link>",
    },
    {
        id: 19,
        question_text: "Tag untuk metadata di dalam <head> adalah?",
        options: ["<meta>", "<data>", "<info>", "<head-data>"],
        correct_answer: "<meta>",
    },
    {
        id: 20,
        question_text: "Deklarasi doctype HTML5 yang benar adalah?",
        options: [
            "<!DOCTYPE html>",
            "<!DOCTYPE HTML5>",
            "<!DOCTYPE>",
            "<doctype html>",
        ],
        correct_answer: "<!DOCTYPE html>",
    },
    {
        id: 21,
        question_text: "Bagaimana menuliskan komentar di HTML?",
        options: ["<!-- komentar -->", "// komentar", "/* komentar */", "# komentar"],
        correct_answer: "<!-- komentar -->",
    },
    {
        id: 22,
        question_text: "Apa kepanjangan dari CSS?",
        options: [
            "Cascading Style Sheets",
            "Computer Style System",
            "Creative Style Syntax",
            "Coded Style Script",
        ],
        correct_answer: "Cascading Style Sheets",
    },
    {
        id: 23,
        question_text: "Bagaimana menambahkan CSS inline pada elemen?",
        options: [
            "Menggunakan atribut style",
            "Menggunakan atribut css",
            "Menggunakan atribut class",
            "Menggunakan atribut id",
        ],
        correct_answer: "Menggunakan atribut style",
    },
    {
        id: 24,
        question_text: "Selector CSS untuk memilih elemen dengan id 'hero' adalah?",
        options: ["#hero", ".hero", "hero", "*hero"],
        correct_answer: "#hero",
    },
    {
        id: 25,
        question_text: "Selector CSS untuk memilih elemen dengan class 'card' adalah?",
        options: [".card", "#card", "card", "*card"],
        correct_answer: ".card",
    },
    {
        id: 26,
        question_text: "Properti CSS untuk mengubah warna teks adalah?",
        options: ["color", "text-color", "font-color", "foreground"],
        correct_answer: "color",
    },
    {
        id: 27,
        question_text: "Properti CSS untuk mengubah warna latar belakang adalah?",
        options: ["background-color", "bg-color", "fill", "background"],
        correct_answer: "background-color",
    },
    {
        id: 28,
        question_text: "Properti CSS untuk mengubah ukuran huruf adalah?",
        options: ["font-size", "text-size", "size", "font"],
        correct_answer: "font-size",
    },
    {
        id: 29,
        question_text: "Properti CSS untuk membuat teks lebih tebal adalah?",
        options: ["font-weight", "text-bold", "bold", "font-bold"],
        correct_answer: "font-weight",
    },
    {
        id: 30,
        question_text: "Properti CSS untuk jarak dalam elemen adalah?",
        options: ["padding", "margin", "gap", "space"],
        correct_answer: "padding",
    },
    {
        id: 31,
        question_text: "Properti CSS untuk jarak luar elemen adalah?",
        options: ["margin", "padding", "gap", "offset"],
        correct_answer: "margin",
    },
    {
        id: 32,
        question_text: "Properti CSS untuk membuat sudut membulat adalah?",
        options: ["border-radius", "corner-radius", "radius", "round"],
        correct_answer: "border-radius",
    },
    {
        id: 33,
        question_text: "Cara paling umum membuat layout fleksibel modern adalah?",
        options: ["display: flex", "display: inline-block", "float", "table"],
        correct_answer: "display: flex",
    },
    {
        id: 34,
        question_text: "Siapa pencipta World Wide Web?",
        options: [
            "Tim Berners-Lee",
            "Vint Cerf",
            "Brendan Eich",
            "Linus Torvalds",
        ],
        correct_answer: "Tim Berners-Lee",
    },
    {
        id: 35,
        question_text: "Tahun berapa situs web pertama kali online di CERN?",
        options: ["1989", "1990", "1991", "1993"],
        correct_answer: "1991",
    },
    {
        id: 36,
        question_text: "Properti untuk mengubah arah flex menjadi kolom?",
        options: ["flex-direction: column", "direction: column", "flow: column", "flex-flow: row"],
        correct_answer: "flex-direction: column",
    },
    {
        id: 37,
        question_text: "Browser web pertama yang populer luas pada awal 1990-an adalah?",
        options: ["Mosaic", "Netscape Navigator", "Internet Explorer", "Lynx"],
        correct_answer: "Mosaic",
    },
    {
        id: 38,
        question_text: "Contoh media query untuk layar kecil adalah?",
        options: [
            "@media (max-width: 600px) { ... }",
            "@media small { ... }",
            "@mobile { ... }",
            "@screen < 600 { ... }",
        ],
        correct_answer: "@media (max-width: 600px) { ... }",
    },
    {
        id: 39,
        question_text: "Tag HTML untuk membuat formulir adalah?",
        options: ["<form>", "<input>", "<fieldset>", "<label>"],
        correct_answer: "<form>",
    },
    {
        id: 40,
        question_text: "Tipe input untuk email agar tervalidasi dasar oleh browser?",
        options: [
            "<input type=\"email\">",
            "<input type=\"text\">",
            "<input type=\"mail\">",
            "<input type=\"username\">",
        ],
        correct_answer: "<input type=\"email\">",
    },
    {
        id: 41,
        question_text: "Tipe input untuk kata sandi adalah?",
        options: [
            "<input type=\"password\">",
            "<input type=\"secret\">",
            "<input type=\"text\">",
            "<input type=\"passwd\">",
        ],
        correct_answer: "<input type=\"password\">",
    },
    {
        id: 42,
        question_text: "Elemen HTML standar untuk tombol adalah?",
        options: ["<button>", "<input>", "<submit>", "<action>"],
        correct_answer: "<button>",
    },
    {
        id: 43,
        question_text: "Atribut formulir untuk URL tujuan pengiriman data adalah?",
        options: ["action", "method", "target", "enctype"],
        correct_answer: "action",
    },
    {
        id: 44,
        question_text: "Atribut formulir untuk metode pengiriman (GET/POST) adalah?",
        options: ["method", "action", "type", "route"],
        correct_answer: "method",
    },
    {
        id: 45,
        question_text: "Atribut pada input untuk teks petunjuk adalah?",
        options: ["placeholder", "hint", "help", "title"],
        correct_answer: "placeholder",
    },
    {
        id: 46,
        question_text: "Atribut pada input agar wajib diisi adalah?",
        options: ["required", "validate", "must", "need"],
        correct_answer: "required",
    },
    {
        id: 47,
        question_text: "Bagaimana mengaitkan <label> dengan <input>?",
        options: [
            "Gunakan for pada label dan id pada input",
            "Gunakan name yang sama",
            "Letakkan bersebelahan",
            "Tidak perlu apa-apa",
        ],
        correct_answer: "Gunakan for pada label dan id pada input",
    },
    {
        id: 48,
        question_text: "Siapa pencipta JavaScript?",
        options: ["Brendan Eich", "James Gosling", "Guido van Rossum", "Anders Hejlsberg"],
        correct_answer: "Brendan Eich",
    },
    {
        id: 49,
        question_text: "Tag untuk judul halaman yang muncul di tab browser adalah?",
        options: ["<title>", "<h1>", "<header>", "<head>"],
        correct_answer: "<title>",
    },
    {
        id: 50,
        question_text: "Tag meta untuk deskripsi halaman (SEO) adalah?",
        options: [
            "<meta name=\"description\" content=\"...\">",
            "<meta name=\"seo\" content=\"...\">",
            "<description>...</description>",
            "<meta desc=\"...\">",
        ],
        correct_answer: "<meta name=\"description\" content=\"...\">",
    },
    {
        id: 51,
        question_text: "Nama berkas default yang biasanya dicari server untuk halaman awal adalah?",
        options: ["index.html", "home.html", "main.html", "start.html"],
        correct_answer: "index.html",
    },
    {
        id: 52,
        question_text: "Apa kepanjangan dari HTTP?",
        options: [
            "HyperText Transfer Protocol",
            "Hyperlink Transfer Protocol",
            "HyperText Transmission Package",
            "High Transfer Text Protocol",
        ],
        correct_answer: "HyperText Transfer Protocol",
    },
    {
        id: 53,
        question_text: "Kode status HTTP 200 berarti?",
        options: ["Berhasil", "Dialihkan", "Tidak ditemukan", "Kesalahan server"],
        correct_answer: "Berhasil",
    },
    {
        id: 54,
        question_text: "Kode status HTTP 404 berarti?",
        options: [
            "Tidak ditemukan",
            "Berhasil",
            "Permintaan tidak valid",
            "Tidak berwenang",
        ],
        correct_answer: "Tidak ditemukan",
    },
    {
        id: 55,
        question_text: "Kode status HTTP 500 berarti?",
        options: [
            "Kesalahan server internal",
            "Berhasil",
            "Dialihkan permanen",
            "Tidak berwenang",
        ],
        correct_answer: "Kesalahan server internal",
    },
    {
        id: 56,
        question_text: "Metode HTTP GET umumnya digunakan untuk?",
        options: ["Mengambil data", "Mengirim berkas", "Menghapus data", "Mengubah data"],
        correct_answer: "Mengambil data",
    },
    {
        id: 57,
        question_text: "Metode HTTP POST umumnya digunakan untuk?",
        options: ["Mengirim/menyimpan data", "Mengambil data", "Menghapus data", "Mengunduh data"],
        correct_answer: "Mengirim/menyimpan data",
    },
    {
        id: 58,
        question_text: "Ekstensi berkas untuk stylesheet adalah?",
        options: [".css", ".style", ".scss", ".sass"],
        correct_answer: ".css",
    },
    {
        id: 59,
        question_text: "Bagaimana cara memasukkan JavaScript ke HTML?",
        options: [
            "Menggunakan tag <script>",
            "Menggunakan tag <js>",
            "Menggunakan tag <code>",
            "Menggunakan tag <javascript>",
        ],
        correct_answer: "Menggunakan tag <script>",
    },
    {
        id: 60,
        question_text: "Kata kunci untuk mendeklarasikan konstanta di JavaScript adalah?",
        options: ["const", "let", "var", "static"],
        correct_answer: "const",
    },
    {
        id: 61,
        question_text: "Contoh literal array di JavaScript adalah?",
        options: ["[1, 2, 3]", "{1,2,3}", "(1,2,3)", "<1,2,3>"],
        correct_answer: "[1, 2, 3]",
    },
    {
        id: 62,
        question_text: "Sintaks arrow function yang benar adalah?",
        options: ["() => {}", "function => {}", "() -> {}", "fn() {}"],
        correct_answer: "() => {}",
    },
    {
        id: 63,
        question_text: "Perintah untuk mencetak ke konsol di JavaScript adalah?",
        options: ["console.log", "print", "echo", "System.out"],
        correct_answer: "console.log",
    },
    {
        id: 64,
        question_text: "Operator perbandingan ketat (nilai dan tipe) adalah?",
        options: ["===", "==", "=", "!=="],
        correct_answer: "===",
    },
    {
        id: 65,
        question_text: "Nama event saat tombol diklik adalah?",
        options: ["click", "press", "tap", "submit"],
        correct_answer: "click",
    },
    {
        id: 66,
        question_text: "Bagaimana memilih elemen dengan id 'app' lewat DOM?",
        options: [
            "document.getElementById('app')",
            "document.query('#app')",
            "document.get('#app')",
            "window.getElement('app')",
        ],
        correct_answer: "document.getElementById('app')",
    },
    {
        id: 67,
        question_text: "Metode DOM untuk memilih elemen pertama yang cocok dengan selector adalah?",
        options: [
            "document.querySelector",
            "document.querySelectorAll",
            "document.select",
            "document.find",
        ],
        correct_answer: "document.querySelector",
    },
    {
        id: 68,
        question_text: "Fungsi untuk mencegah aksi default (misal submit form) adalah?",
        options: [
            "event.preventDefault()",
            "event.stop()",
            "event.cancel()",
            "event.block()",
        ],
        correct_answer: "event.preventDefault()",
    },
    {
        id: 69,
        question_text: "Event yang menandakan DOM sudah siap diproses adalah?",
        options: ["DOMContentLoaded", "load", "ready", "initialized"],
        correct_answer: "DOMContentLoaded",
    },
    {
        id: 70,
        question_text: "Cara menambahkan class 'active' pada elemen di JS?",
        options: [
            "element.classList.add('active')",
            "element.addClass('active')",
            "element.class('active')",
            "element.classes.push('active')",
        ],
        correct_answer: "element.classList.add('active')",
    },
    {
        id: 71,
        question_text: "Cara mengubah teks elemen paragraf di JS adalah?",
        options: [
            "p.textContent = '...'",
            "p.value = '...'",
            "p.innerValue = '...'",
            "p.text = '...'",
        ],
        correct_answer: "p.textContent = '...'",
    },
    {
        id: 72,
        question_text: "Sebelum bernama JavaScript, namanya sempat diganti menjadi?",
        options: ["LiveScript", "Mocha", "ECMAScript", "ActionScript"],
        correct_answer: "LiveScript",
    },
    {
        id: 73,
        question_text: "Cookie pada browser digunakan untuk?",
        options: [
            "Menyimpan data kecil yang ikut terkirim ke server",
            "Menyimpan file besar di klien",
            "Mempercepat CPU",
            "Menambah RAM",
        ],
        correct_answer: "Menyimpan data kecil yang ikut terkirim ke server",
    },
    {
        id: 74,
        question_text: "Tag untuk menautkan favicon adalah?",
        options: [
            "<link rel=\"icon\" href=\"...\">",
            "<meta rel=\"icon\" href=\"...\">",
            "<icon src=\"...\">",
            "<fav href=\"...\">",
        ],
        correct_answer: "<link rel=\"icon\" href=\"...\">",
    },
    {
        id: 75,
        question_text: "Gambar terkenal pertama yang diunggah ke web menampilkan?",
        options: [
            "Les Horribles Cernettes",
            "Logo CERN",
            "Potret Tim Berners-Lee",
            "Lambang WWW",
        ],
        correct_answer: "Les Horribles Cernettes",
    },
    {
        id: 76,
        question_text: "Nama domain .com pertama yang didaftarkan pada tahun 1985 adalah?",
        options: ["symbolics.com", "apple.com", "bbn.com", "xerox.com"],
        correct_answer: "symbolics.com",
    },
    {
        id: 77,
        question_text: "CSS untuk membuat elemen melayang ke kanan adalah?",
        options: ["float: right", "position: right", "display: right", "align: right"],
        correct_answer: "float: right",
    },
    {
        id: 78,
        question_text: "Urutan box model CSS dari dalam ke luar adalah?",
        options: [
            "content, padding, border, margin",
            "content, border, padding, margin",
            "padding, content, border, margin",
            "margin, border, padding, content",
        ],
        correct_answer: "content, padding, border, margin",
    },
    {
        id: 79,
        question_text: "Cara umum menghapus margin/padding default semua elemen?",
        options: [
            "* { margin: 0; padding: 0; }",
            "html { reset: all }",
            "body { clean: true }",
            "reset()",
        ],
        correct_answer: "* { margin: 0; padding: 0; }",
    },
    {
        id: 80,
        question_text: "Siapa yang pertama kali mengusulkan CSS pada tahun 1994?",
        options: ["Håkon Wium Lie", "Bert Bos", "Tim Berners-Lee", "John Resig"],
        correct_answer: "Håkon Wium Lie",
    },
    {
        id: 81,
        question_text: "Unit CSS yang mewakili 1% lebar viewport adalah?",
        options: ["vw", "vh", "%", "vmin"],
        correct_answer: "vw",
    },
    {
        id: 82,
        question_text: "HTML5 dirilis sebagai Rekomendasi W3C pada tahun?",
        options: ["2008", "2012", "2014", "2016"],
        correct_answer: "2014",
    },
    {
        id: 83,
        question_text: "Konsep arsitektur REST diperkenalkan oleh siapa?",
        options: ["Roy Fielding", "Linus Torvalds", "Ken Thompson", "James Gosling"],
        correct_answer: "Roy Fielding",
    },
    {
        id: 84,
        question_text: "Sistem version control yang populer untuk proyek web adalah?",
        options: ["Git", "SVN", "Mercurial", "CVS"],
        correct_answer: "Git",
    },
    {
        id: 85,
        question_text: "Perintah untuk menginisialisasi repository Git adalah?",
        options: ["git init", "git start", "git new", "git create"],
        correct_answer: "git init",
    },
    {
        id: 86,
        question_text: "Perintah untuk menambahkan file ke staging area di Git adalah?",
        options: ["git add", "git stage", "git push", "git commit"],
        correct_answer: "git add",
    },
    {
        id: 87,
        question_text: "Perintah untuk membuat commit di Git adalah?",
        options: [
            "git commit -m \"pesan\"",
            "git save -m \"pesan\"",
            "git push -m \"pesan\"",
            "git log -m \"pesan\"",
        ],
        correct_answer: "git commit -m \"pesan\"",
    },
    {
        id: 88,
        question_text: "Perusahaan yang memperkenalkan SSL (cikal bakal HTTPS) pada 1990-an adalah?",
        options: ["Netscape", "Microsoft", "Sun Microsystems", "IBM"],
        correct_answer: "Netscape",
    },
    {
        id: 89,
        question_text: "Mesin pencari yang populer sebelum Google pada era 1990-an adalah?",
        options: ["AltaVista", "Bing", "DuckDuckGo", "Baidu"],
        correct_answer: "AltaVista",
    },
    {
        id: 90,
        question_text: "React pertama kali diperkenalkan ke publik pada tahun?",
        options: ["2010", "2011", "2013", "2015"],
        correct_answer: "2013",
    },
    {
        id: 91,
        question_text: "Node.js pertama dirilis pada tahun?",
        options: ["2006", "2009", "2012", "2015"],
        correct_answer: "2009",
    },
    {
        id: 92,
        question_text: "Git diciptakan oleh siapa?",
        options: ["Linus Torvalds", "Guido van Rossum", "Larry Page", "James Gosling"],
        correct_answer: "Linus Torvalds",
    },
    {
        id: 93,
        question_text: "Siapa yang mempopulerkan JSON sebagai format pertukaran data ringan?",
        options: ["Douglas Crockford", "Brendan Eich", "Tim Bray", "Yukihiro Matsumoto"],
        correct_answer: "Douglas Crockford",
    },
    {
        id: 94,
        question_text: "Tag untuk garis horizontal pemisah adalah?",
        options: ["<hr>", "<line>", "<rule>", "<separator>"],
        correct_answer: "<hr>",
    },
    {
        id: 95,
        question_text: "Tag untuk pindah baris (line break) adalah?",
        options: ["<br>", "<lb>", "<nl>", "<newline>"],
        correct_answer: "<br>",
    },
    {
        id: 96,
        question_text: "Tag untuk menandai teks penting/tebal secara semantik adalah?",
        options: ["<strong>", "<b>", "<em>", "<i>"],
        correct_answer: "<strong>",
    },
    {
        id: 97,
        question_text: "Tag untuk menandai penekanan/teks miring secara semantik adalah?",
        options: ["<em>", "<i>", "<italic>", "<m>"],
        correct_answer: "<em>",
    },
    {
        id: 98,
        question_text: "Kode status 418 dalam RFC 2324 (lelucon) berarti?",
        options: ["I'm a teapot", "Coffee break", "April Fools", "Unused"],
        correct_answer: "I'm a teapot",
    },
    {
        id: 99,
        question_text: "Server web pertama di dunia berjalan pada komputer apa di CERN?",
        options: ["NeXTcube", "IBM PC", "Macintosh", "SUN Workstation"],
        correct_answer: "NeXTcube",
    },
    {
        id: 100,
        question_text: "Atribut <a> yang disarankan saat menggunakan target=\"_blank\" demi keamanan adalah?",
        options: [
            "rel=\"noopener noreferrer\"",
            "rel=\"external\"",
            "rel=\"nofollow\"",
            "rel=\"noopener\" saja",
        ],
        correct_answer: "rel=\"noopener noreferrer\"",
    },
];

export default questions;

